name: mapperapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.1

  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.5.1
  flutter_speed_dial: ^7.0.0
  image_picker: ^0.8.5+3
  fl_chart: ^1.1.1
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/svgVectors/

# 🟢 Localization setup (خارج قسم flutter)
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: strings.dart
  output-class: Strings
