// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEzTLL1sR16NHoX0Fm0L8UsotRxMgOII',
    appId: '1:1075749046066:web:103a2aa39ba0e9e052f92b',
    messagingSenderId: '1075749046066',
    projectId: 'step-done-418a3',
    authDomain: 'step-done-418a3.firebaseapp.com',
    storageBucket: 'step-done-418a3.firebasestorage.app',
    measurementId: 'G-GFXFV3KZGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1-0CzZqeUj191nPxxKK9ZmvuUF4CaP0',
    appId: '1:1075749046066:android:9f7fe0d3ad06d7ba52f92b',
    messagingSenderId: '1075749046066',
    projectId: 'step-done-418a3',
    storageBucket: 'step-done-418a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyHxD1-xp6_RcOyJw6okYSO_cANAYz8E',
    appId: '1:1075749046066:ios:e146672d82501c7a52f92b',
    messagingSenderId: '1075749046066',
    projectId: 'step-done-418a3',
    storageBucket: 'step-done-418a3.firebasestorage.app',
    iosBundleId: 'com.example.mapperapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWyHxD1-xp6_RcOyJw6okYSO_cANAYz8E',
    appId: '1:1075749046066:ios:e146672d82501c7a52f92b',
    messagingSenderId: '1075749046066',
    projectId: 'step-done-418a3',
    storageBucket: 'step-done-418a3.firebasestorage.app',
    iosBundleId: 'com.example.mapperapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBEzTLL1sR16NHoX0Fm0L8UsotRxMgOII',
    appId: '1:1075749046066:web:1237a269416edfe452f92b',
    messagingSenderId: '1075749046066',
    projectId: 'step-done-418a3',
    authDomain: 'step-done-418a3.firebaseapp.com',
    storageBucket: 'step-done-418a3.firebasestorage.app',
    measurementId: 'G-KDE75ZD2HD',
  );
}
